# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build and push HTML

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python deps
        run: |
              python3.12 -m venv venv
              source venv/bin/activate
              make install
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Node deps
        run: |
              npm install -g staticrypt
      - name: Setup Env & Run
        run: |
              export STATICRYPT_PASSWORD=${{ secrets.STATICRYPT_PASSWORD }}
              source venv/bin/activate
              make run
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Commit changes
        run: |
          git config --local user.name "Daintta Bot"
          git config --local user.email "harry.wixley@daintta.com"
          git fetch origin
          export BRANCH="${{ steps.extract_branch.outputs.branch }}"
          echo "BRANCH: !! ${BRANCH} !!"
          git checkout -b ${BRANCH}
          git add src/generated/index.html encrypted/index.html
          git commit -m "GH-Action: auto-update HTML"
          git push origin ${BRANCH}