# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build and push HTML

on:
  # Runs on pushes targeting the default branch
  push:
    paths:
    - src/templates/base.html
    - src/data/**
    - .github/README_TEMPLATE.md

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: |
              python3.12 -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
              python3.12 src/__init__.py

      # Commit and push changes
      - name: Commit changes
        run: |
          git config --local user.name "Daintta Bot"
          git config --local user.email "harry.wixley@daintta.com"
          export BRANCH=$(git symbolic-ref --short HEAD)
          git pull origin ${BRANCH}
          git add src/generated/index.html
          git commit -m "GH-Action: auto-update HTML"
          git push origin ${BRANCH}