# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build and push HTML

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: |
              python3.12 -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
              python3.12 src/__init__.py
              ls
              git status
              cat src/generated/index.html
